#!usr/bin/env/python3
# Name: Pulkit Nayyar
# SID: 152096210

import os
import pwd

def userexist(username):             # Function to Check if the user provided exists
    userslist = pwd.getpwall()
    # getpwall() returns a list of users represented in tuple with various user details like username, user id etc
    for user in userslist:
        #loops through each user through the list
        if user.pw_name == username:
            # pw_name is one of the attribute which fetches just the username.
            return True
            # Returns true if username is found in the list
    return False
    # Returns False if username is not in the list 

def makesudoer():                    # Function to grant Sudo access to a specified user
    user = input("Enter the user to escalate permissions: ").strip()
    # getting the user to make changes to .strip() is used to remove any accidental and unwanted spaces or newline characters
    if not user:
    # input control code to check empty inputs
        print("Error: Please provide a user.")
        # Prints a general message asking for an input and exits the function if no user is provided
        return

    if userexist(user):
    # calls userexists(user) function if True proceeds with the inside code, if False executes the else block
        try:
            os.system(f"sudo usermod -aG sudo {user}")
            # os.system() is used to execute a command in shell or as command is executed in terminal 
            print(f"{user} has been added to the sudoers.")
            # prints a message of succesful execution and function performed
        except Exception:
            # It is used to catch any Exception generated by the try block
            print(f"Error: Cannot add '{user}' to the sudoers.")
            # prints a friendly message of what the function could not perform
            print(Exception)
            # prints the Error/Exception generated while execution
    else:
        print(f"{user} does not exist")
        # prints the helfful message if userexist() function could not find the user

def updatepasswd():                  # Function to change/update password for a user
    user = input("Enter the user to change the password: ").strip()
    # getting the user to make changes to .strip() is used to remove any accidental and unwanted spaces or newline characters
    if not user:
    # input control code to check empty inputs
        print("Error: no user provided.")
        # Prints a general message asking for an input and exits the function if no user is provided
        return

    if userexist(user):
    # calls userexists(user) function if True proceeds with the inside code, if False executes the else block
        try:
            print(f"Changing password for user '{user}'.")
            # prints a helpfull message indicating what function is being performed on which user 
            os.system(f"sudo passwd {user}")
            # another way of executing shell commands directly from the python code using subprocess.run
            # check = True is used for error handling similar to while True. if any error is generated while executing the command 
            # it jumps the cursor to catch/except block for handling
            print(f"Password for user '{user}' updated")
            # if above process is success, prints a message of successfull execution and function performed.
        except Exception:
            print(f"Error: Cannot change password for user '{user}'.")
            print(Exception)
    else:
        print(f"user: {user} does not exist.")

def removesudoer():                  # Function to remove sudo privilages for a specified user
    user = input("Enter the user to remove sudo access: ").strip()
    if not user:
        print("Error: Please provide a user.")
        return
    # Same code to check for empty input
    if userexist(user): 
        try:
            os.system(f"sudo deluser {user} sudo")
            # used to execute a shell command using os.system() 
            # sudo deluser can also be used to remove a user entirely but here the sudo mentioned at the end of the command signifies the group from which the user needs to be deleted.
            print(f"{user} has been removed from the sudoers.")
        except Exception:
            # Error Handling
            print(f"Error: Cannot remove '{user}' from the sudoers.")
            print(Exception)
    else:
        print(f"{user} does not exist")

    
def update_user():                  # Main Function
    """
    This function will update user permissions and password
    """
    print("Please choose an option:")           # Simple way of printing a menu of the functionalities available
    print("1. Change a user password")
    print("2. Make a user sudoer")
    print("3. Remove sudo access from a user ")
    print("4. exit")
    
    try:
        opt = int(input("Enter your option: ").strip())
        # Storing the choice into a variable for further processing
    except ValueError:
        # Error handing for an invalid input
        print("Invalid option")
        return

    if opt == 1:
        updatepasswd()
        # calls the function updatepasswd() if input is 1
    elif opt == 2:
        makesudoer()
        # calls the function makesudoer if input is 2
    elif opt == 3:
        removesudoer()
        # calls the function removesudoer if input is 3
    elif opt == 4:
        print("----------Exiting----------.")
        # exits the function if input printing a message if input is 4
        return
    else:
        print("Invalid option")
        # prints a message if input is out of scope

